# Generated by Django 4.2.2 on 2023-06-08 07:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveOpps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('deadline', models.DateTimeField()),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('link', models.CharField()),
                ('typeOfOpp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
                ('approved', models.BooleanField()),
                ('keywords', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=75), size=None)),
            ],
        ),
    ]
