# Generated by Django 4.2.2 on 2023-06-10 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunitiesDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeopps',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
