# Generated by Django 4.2.2 on 2023-06-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunitiesDB', '0003_activeopps_createdat_activeopps_websitename'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeopps',
            name='titleAI',
            field=models.CharField(default='placeholder', max_length=150),
            preserve_default=False,
        ),
    ]
