# Generated by Django 4.2.2 on 2023-06-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunitiesDB', '0004_activeopps_titleai'),
    ]

    operations = [
        migrations.AddField(
            model_name='activeopps',
            name='deadlineString',
            field=models.CharField(default='January 1, 2023', max_length=50),
            preserve_default=False,
        ),
    ]
