# Generated by Django 4.2.2 on 2024-07-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunitiesDB', '0006_alter_activeopps_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeopps',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='activeopps',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='activeopps',
            name='titleAI',
            field=models.CharField(max_length=250),
        ),
    ]
